# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/zedboard_master.xdc

# IP: ip/init_sequence_rom/init_sequence_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: ip/pixel_buffer/pixel_buffer.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# IP: ip/charLib/charLib.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: ip/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: ip/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: ip/charLib/charLib_ooc.xdc
