# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Fuentes/zedboard_constraint.xdc

# Block Designs: bd/controlador_pwm/controlador_pwm.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controlador_pwm || ORIG_REF_NAME==controlador_pwm} -quiet] -quiet

# IP: bd/controlador_pwm/ip/controlador_pwm_cont_preescalado_0_1/controlador_pwm_cont_preescalado_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controlador_pwm_cont_preescalado_0_1 || ORIG_REF_NAME==controlador_pwm_cont_preescalado_0_1} -quiet] -quiet

# IP: bd/controlador_pwm/ip/controlador_pwm_mod_m_counter_0_0/controlador_pwm_mod_m_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controlador_pwm_mod_m_counter_0_0 || ORIG_REF_NAME==controlador_pwm_mod_m_counter_0_0} -quiet] -quiet

# IP: bd/controlador_pwm/ip/controlador_pwm_pwm_dc_motor_0_0/controlador_pwm_pwm_dc_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==controlador_pwm_pwm_dc_motor_0_0 || ORIG_REF_NAME==controlador_pwm_pwm_dc_motor_0_0} -quiet] -quiet

# XDC: bd/controlador_pwm/controlador_pwm_ooc.xdc
