# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Fuentes/zedboard_constraint.xdc

# Block Designs: bd/control_motores/control_motores.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores || ORIG_REF_NAME==control_motores} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_control_direccion_0_0/control_motores_control_direccion_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_control_direccion_0_0 || ORIG_REF_NAME==control_motores_control_direccion_0_0} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_decoder_0_0/control_motores_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_decoder_0_0 || ORIG_REF_NAME==control_motores_decoder_0_0} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_mod_m_counter_0_0/control_motores_mod_m_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_mod_m_counter_0_0 || ORIG_REF_NAME==control_motores_mod_m_counter_0_0} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_pwm_dc_motor_0_0/control_motores_pwm_dc_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_pwm_dc_motor_0_0 || ORIG_REF_NAME==control_motores_pwm_dc_motor_0_0} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_pwm_dc_motor_1_0/control_motores_pwm_dc_motor_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_pwm_dc_motor_1_0 || ORIG_REF_NAME==control_motores_pwm_dc_motor_1_0} -quiet] -quiet

# IP: bd/control_motores/ip/control_motores_control_direccion_1_0/control_motores_control_direccion_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motores_control_direccion_1_0 || ORIG_REF_NAME==control_motores_control_direccion_1_0} -quiet] -quiet

# XDC: bd/control_motores/control_motores_ooc.xdc
