# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Fuentes/zedboard_constraint.xdc

# Block Designs: bd/control_motor/control_motor.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motor || ORIG_REF_NAME==control_motor} -quiet] -quiet

# IP: bd/control_motor/ip/control_motor_pwm_dc_motor_0_0/control_motor_pwm_dc_motor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motor_pwm_dc_motor_0_0 || ORIG_REF_NAME==control_motor_pwm_dc_motor_0_0} -quiet] -quiet

# IP: bd/control_motor/ip/control_motor_cont_preescalado_0_1/control_motor_cont_preescalado_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==control_motor_cont_preescalado_0_1 || ORIG_REF_NAME==control_motor_cont_preescalado_0_1} -quiet] -quiet

# XDC: bd/control_motor/control_motor_ooc.xdc
